//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEcoImagen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respaldo
    {
        public int idRespaldo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaSubida { get; set; }
        public string nombreArchivo { get; set; }
        public string rutaFisica { get; set; }
        public Nullable<int> tamano { get; set; }
        public string enlaceDescarga { get; set; }
        public string nodoContenedor { get; set; }
        public string estado { get; set; }
    }
}
