//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEcoImagen
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Seguimiento
    {
        public int idSeguimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string sintomas { get; set; }
        public string resultado { get; set; }
        public string medicoReferente { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<System.DateTime> borrado { get; set; }
        public string tipoSeguimiento { get; set; }
        public Nullable<int> ct { get; set; }
        public Nullable<int> gn { get; set; }
        public Nullable<int> cm { get; set; }
        [JsonIgnore]
        public virtual Paciente Paciente { get; set; }
    }
}
